name: 'snowflake_workshop'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  snowflake_workshop:
    staging:
      materialized: view
      snowflake_warehouse: small_wh
    marts:
      materialized: table
      snowflake_warehouse: small_wh    
    CJ_Playground:
      materialized: table
      snowflake_warehouse: small_wh          

      CJ_Playground1:
        materialized: view
        snowflake_warehouse: small_wh                